### PR TITLE
Make God#stop_all consistent with God#control

### PR DESCRIPTION
**Pull request by carsonreinke**
Hopefully fixing https://github.com/mojombo/god/issues/189.  I have not included a test, unsure how to with this complex issue.

### CODE REVIEW

**Comment by evanbattaglia** [comment]
:+1: seems to work for me!

**Comment by carsonreinke** [comment]
@lukeasrodgers I merged in your tests into this PR, hopefully some day to get some resolution on this.

**Comment by groe** [comment]
Is there something blocking the merge of this PR? I have been struggling with #189 for a long time now and would love to see a fix merged for this.

**Comment by eric** [comment]
Seems reasonable to me.

**Comment by groe** [comment]
@eric Awesome, thank you very much! Looking forward to 0.13.7 :)

**Pull request merged**
